version: "3"
services:
  pv_data_pipeline_disambiguation_worker:
    healthcheck:
      test: [ "airflow", "db", "check" ]
      interval: 2m
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - pv_update_volume:/data-volume/
      - '{path_to_project_folder}/PatentsView-DB/:/project'
      - '{path_to_project_folder}/PatentsView-DB/PatentsView-DB/.my.cnf:/home/airflow/.my.cnf'
      - '{path_to_project_folder}/PatentsView-DB/PatentsView/PatentsView-DB/airflow/:/airflow'
      - '{path_to_project_folder}/PatentsView-DB/:/project/updater/disambiguation/hierarchical_clustering_disambiguation/data/'
      - '{path_to_project_folder}/PatentsView-DB/PatentsView-DB/clustering_resources/:/project/clustering_resources/'
    image: update_pipeline_20221206
    restart: on-failure:5
    ports:
      - 8793:8793
    env_file:
      - airflow_pipeline_env.sh
    container_name:   pv_data_pipeline_disambiguation_worker
    command:
      - celery
      - worker
      - -q
      - disambiguation
    extra_hosts:
      - "airflow_database:{Internal IP address of Airflow Database Server}"
      - "airflow-broker:{Internal IP address of Airflow Broker Server}"